# Generated by Django 3.2 on 2022-10-05 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 11, 59, 7, 292164)),
        ),
    ]
