# Generated by Django 3.2 on 2022-09-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('user_surname', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=250)),
                ('price', models.PositiveSmallIntegerField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
