# Generated by Django 3.2 on 2022-10-06 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_blog', '0005_alter_order_created_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 13, 52, 13, 990978)),
        ),
    ]
